-- Chicken on Wheels database
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_date text not null,
  event_time text,
  guest_count integer,
  event_type text,
  location text not null,
  details text,
  status text not null default 'pending',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add fields when upgrading a booking_requests table created by an older schema.
alter table public.booking_requests
  add column if not exists event_time text,
  add column if not exists guest_count integer,
  add column if not exists event_type text,
  add column if not exists details text,
  add column if not exists admin_note text;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  customer_note text,
  item_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.truck_schedule (
  id bigint generated by default as identity primary key,
  service_date date not null unique,
  status text not null default 'opening_soon' check (status in ('open', 'closed', 'opening_soon')),
  location_name text not null,
  address text,
  schedule text,
  directions_url text,
  map_embed_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  reviewer_name text not null,
  rating integer not null check (rating between 1 and 5),
  quote text not null,
  source text,
  created_at timestamptz not null default now()
);

create index if not exists booking_requests_user_id_idx
  on public.booking_requests(user_id);

create index if not exists booking_requests_status_idx
  on public.booking_requests(status);

create index if not exists orders_user_id_idx
  on public.orders(user_id);

create index if not exists orders_status_idx
  on public.orders(status);

create index if not exists truck_schedule_service_date_idx
  on public.truck_schedule(service_date);

alter table public.profiles enable row level security;
alter table public.booking_requests enable row level security;
alter table public.orders enable row level security;
alter table public.truck_schedule enable row level security;
alter table public.reviews enable row level security;

-- Check admin status without recursively evaluating profiles RLS policies.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Profile policies
drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles"
on public.profiles for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can update profiles" on public.profiles;
create policy "Admins can update profiles"
on public.profiles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Booking policies
alter table public.booking_requests
  drop constraint if exists booking_requests_status_check;

-- Normalize values from older versions before validating the new status set.
update public.booking_requests
set status = case lower(trim(status))
  when 'accepted' then 'confirmed'
  when 'under review' then 'under_review'
  when 'in review' then 'under_review'
  when 'declined' then 'rejected'
  when 'cancelled' then 'rejected'
  when '' then 'pending'
  else lower(trim(status))
end
where status is distinct from lower(trim(status))
   or lower(trim(status)) in ('accepted', 'under review', 'in review', 'declined', 'cancelled', '');

alter table public.booking_requests
  add constraint booking_requests_status_check
  check (status in ('pending', 'under_review', 'confirmed', 'rejected', 'completed'));

alter table public.booking_requests
  alter column status set default 'pending';

drop policy if exists "Users can create their own booking requests" on public.booking_requests;
create policy "Users can create their own booking requests"
on public.booking_requests for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can read their own booking requests" on public.booking_requests;
create policy "Users can read their own booking requests"
on public.booking_requests for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can update booking requests" on public.booking_requests;
create policy "Admins can update booking requests"
on public.booking_requests for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete booking requests" on public.booking_requests;
create policy "Admins can delete booking requests"
on public.booking_requests for delete
to authenticated
using (public.is_admin());

-- Orders policies
drop policy if exists "Users can create their own orders" on public.orders;
create policy "Users can create their own orders"
on public.orders for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can read their own orders" on public.orders;
create policy "Users can read their own orders"
on public.orders for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
on public.orders for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete orders" on public.orders;
create policy "Admins can delete orders"
on public.orders for delete
to authenticated
using (public.is_admin());

-- Public read-only tables for truck status and reviews.
drop policy if exists "Anyone can read truck schedule" on public.truck_schedule;
create policy "Anyone can read truck schedule"
on public.truck_schedule for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can read reviews" on public.reviews;
create policy "Anyone can read reviews"
on public.reviews for select
to anon, authenticated
using (true);

-- Automatically create a profile after signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Backfill profiles for accounts created before this trigger was installed.
insert into public.profiles (id, name, email)
select
  id,
  coalesce(raw_user_meta_data ->> 'name', split_part(email, '@', 1)),
  email
from auth.users
where email is not null
on conflict (id) do nothing;

-- Refresh the API schema cache after applying the migrations above.
notify pgrst, 'reload schema';
